# This file was generated by GoReleaser. DO NOT EDIT.
cask "crucible" do
  name "crucible"
  desc "Autonomous software development orchestrator"
  homepage "https://github.com/dmora/crucible"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crucible"
  bash_completion "completions/crucible.bash"
  zsh_completion "completions/crucible.zsh"
  fish_completion "completions/crucible.fish"

  on_macos do
    on_intel do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Darwin_x86_64.tar.gz"
      sha256 "ccc2bab9950027cd23a9eb820bc53b74ec67757b343a8efcbcc2ac08d64e7a07"
    end
    on_arm do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Darwin_arm64.tar.gz"
      sha256 "ad1fd8f2b46c382234ebfe48494bbbc4c60237c84b4a55b6f6b936408027a20f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Linux_x86_64.tar.gz"
      sha256 "e4114951950331053fa1e011c362f0663a77b074eba9af6a419d95423d61e86b"
    end
    on_arm do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Linux_arm64.tar.gz"
      sha256 "6ff6210e9a78c0e636f6e180f024df37d3d4bcdbec2f665d5bcf4c4cefa1c44d"
    end
  end

  # No zap stanza required
end
