# This file was generated by GoReleaser. DO NOT EDIT.
cask "crucible" do
  name "crucible"
  desc "Autonomous software development orchestrator"
  homepage "https://github.com/dmora/crucible"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crucible"
  bash_completion "completions/crucible.bash"
  zsh_completion "completions/crucible.zsh"
  fish_completion "completions/crucible.fish"

  on_macos do
    on_intel do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Darwin_x86_64.tar.gz"
      sha256 "f4ccad3e0e6b095f11d7668609cf5688a67a6ab0856073ff41e601c6303aae96"
    end
    on_arm do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Darwin_arm64.tar.gz"
      sha256 "05265a31044abae63696265106542515247d56c51a02450ea082c90aa70a04f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Linux_x86_64.tar.gz"
      sha256 "fe2a3371bf8f03844917dace853e7ceb3a0fd0b5fd7787bd16ad01f63129bc73"
    end
    on_arm do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Linux_arm64.tar.gz"
      sha256 "d4bf95ebe8ffc9ff628c7339734edd26ce14d30e0385929b8dd4878a0c6ae1e6"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crucible"]
  end

  caveats do
    "If macOS blocks the binary, run: xattr -d com.apple.quarantine $(which crucible)"
  end

  # No zap stanza required
end
