# This file was generated by GoReleaser. DO NOT EDIT.
cask "crucible" do
  name "crucible"
  desc "Autonomous software development orchestrator"
  homepage "https://github.com/dmora/crucible"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crucible"
  bash_completion "completions/crucible.bash"
  zsh_completion "completions/crucible.zsh"
  fish_completion "completions/crucible.fish"

  on_macos do
    on_intel do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Darwin_x86_64.tar.gz"
      sha256 "826f17f30f919c9f80fe7e5cf980991224c817307658096ecc0c7ca1128daa61"
      rename "crucible_0.1.0_Darwin_x86_64/crucible", "crucible"
    end
    on_arm do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Darwin_arm64.tar.gz"
      sha256 "5f4fb6c33fc425d053d1eb52b5c92103aa5aa50d31beed6662a10e4d930ff614"
      rename "crucible_0.1.0_Darwin_arm64/crucible", "crucible"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Linux_x86_64.tar.gz"
      sha256 "efe64236ab6e9c0ace022f696ed95444a1b8eceaa2b5ca146c15bf38114d8c4d"
      rename "crucible_0.1.0_Linux_x86_64/crucible", "crucible"
    end
    on_arm do
      url "https://github.com/dmora/crucible/releases/download/v#{version}/crucible_#{version}_Linux_arm64.tar.gz"
      sha256 "5cebdd03da2fdf86d8295fed98e32babd39bd86b9ea702a6ce00c7d57134ddad"
      rename "crucible_0.1.0_Linux_arm64/crucible", "crucible"
    end
  end

  # No zap stanza required
end
